server:
  port: 9000

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
#        - id: first-service
#          uri: http://127.0.0.1:9001
#          predicates:
#            - Path=/first-service/**
#        - id: second-service
#          uri: http://127.0.0.1:9002
#          predicates:
#            - Path=/second-service/**
#      default-filters:
#        - name: GlobalFilter
#          args:
#            baseMessage: Spring Cloud Gateway Global Filter
#            preLogger: true
#            postLogger: true